CREATE MULTISET TABLE FAB_TEST.UPLOAD_REGISTRY
 ( FAB_ID INTEGER NOT NULL ,
   STUDY_NUMBER VARCHAR(25) NOT NULL,
   TABULATION_DATA_STD VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC,
   ANALYSIS_DATA_STD VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC,
   ETMF_LINK VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
   ENTIMICE_LOCATION VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
   DESCRIPTION VARCHAR(10000) CHARACTER SET UNICODE NOT CASESPECIFIC,
   UPLOADER_ID VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
   UPLOADED_FILE_NAME VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
   JIRA_ID VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC,
   JIRA_LINK VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
   CREATED TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(0) NOT NULL,
   LAST_MODIFIED TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(0) NOT NULL
 )
 UNIQUE PRIMARY INDEX (FAB_ID);